---
name: example-koboldcpp

services:
  koboldcpp:
    build:
      dockerfile: ./llama.cpp/rocm/Dockerfile
      context: ../..
    image: ghcr.io/futursolo/pai-apps/llama.cpp:rocm
    devices:
      - /dev/dri
      - /dev/kfd
    environment:
      HSA_OVERRIDE_GFX_VERSION: 11.0.0
    group_add:
      - video
      - render
    ports:
      - 5001:5001
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    volumes:
      - read_only: true
        source: ../../../test-models
        target: /mnt/models
        type: bind
