---
name: example-base

services:
  blas-rocm:
    build:
      dockerfile: ./_base/blas-rocm/Dockerfile
      context: ../..
    image: ghcr.io/futursolo/pai-apps/base:blas-rocm
    devices:
      - /dev/dri
      - /dev/kfd
    environment:
      HSA_OVERRIDE_GFX_VERSION: 11.0.0
      PYTORCH_ROCM_ARCH: gfx1100
    group_add:
      - video
      - $GROUP_ID_RENDER  # See README.md about how to obtain this ID.
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
