---
name: build-koboldcpp

services:
  rocm:
    build:
      dockerfile: ./koboldcpp/rocm/Dockerfile
      context: ../
      target: build-final
      args:
        - ROCM_DEV_IMAGE=rocm/dev-ubuntu-24.04:7.2.4-complete
        - BLAS_ROCM_BASE_IMAGE=ghcr.io/futursolo/pai-apps/base:blas-rocm-v7.2.4-20260610
        - KOBOLDCPP_VERSION=v1.116.1
    platform: linux/amd64
    image: ghcr.io/futursolo/pai-apps/koboldcpp:v1.116.1-rocm-v7.2.4${PAI_BUILD_VERSION_SUFFIX}
  rocm-variant:
    extends: rocm
    image: ghcr.io/futursolo/pai-apps/koboldcpp:rocm${PAI_BUILD_VARIANT_SUFFIX}

  vulkan:
    build:
      dockerfile: ./koboldcpp/vulkan/Dockerfile
      context: ../
      target: build-final
      args:
        - BLAS_ROCM_BASE_IMAGE=ghcr.io/futursolo/pai-apps/base:vulkan-20260610
        - KOBOLDCPP_VERSION=v1.116.1
    platform: linux/amd64
    image: ghcr.io/futursolo/pai-apps/koboldcpp:v1.116.1-vulkan${PAI_BUILD_VERSION_SUFFIX}
  vulkan-variant:
    extends: vulkan
    image: ghcr.io/futursolo/pai-apps/koboldcpp:vulkan${PAI_BUILD_VARIANT_SUFFIX}
