---
name: example-base

services:
  intel:
    build:
      dockerfile: ./_base/intel/Dockerfile
      context: ../..
      target: build-intel-final
    image: ghcr.io/futursolo/pai-apps/base:intel
    devices:
      - /dev/dri
    group_add:
      - video
      - $GROUP_ID_RENDER  # See README.md about how to obtain this ID.
    restart: unless-stopped

    # WSL Only
    privileged: true
    # WSL Only
    volumes:
      - /usr/lib/wsl:/usr/lib/wsl

  pytorch-xpu:
    build:
      dockerfile: ./_base/pytorch-ipex/Dockerfile
      context: ../..
      target: build-pytorch-xpu-final
    image: ghcr.io/futursolo/pai-apps/base:pytorch-xpu
    # image: intelanalytics/ipex-llm-inference-cpp-xpu:latest
    devices:
      - /dev/dri
    group_add:
      - video
      - $GROUP_ID_RENDER  # See README.md about how to obtain this ID.

    # WSL Only
    privileged: true
    # WSL Only
    volumes:
      - /usr/lib/wsl:/usr/lib/wsl

    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
