---
name: build-comfyui

services:
  rocm:
    build:
      dockerfile: ./comfyui/rocm/Dockerfile
      context: ../
      target: build-final
      args:
        - PYTORCH_BASE_IMAGE=ghcr.io/futursolo/pai-apps/base:pytorch-v2.12.0-rocm-v7.14.0-20260817
        - COMFYUI_VERSION=v0.36.0
    platform: linux/amd64
    image: ghcr.io/futursolo/pai-apps/comfyui:v0.36.0-pytorch-v2.12.0-rocm-v7.14.0${PAI_BUILD_VERSION_SUFFIX}
  rocm-variant:
    extends: rocm
    image: ghcr.io/futursolo/pai-apps/comfyui:rocm${PAI_BUILD_VARIANT_SUFFIX}

  xpu:
    build:
      dockerfile: ./comfyui/xpu/Dockerfile
      context: ../
      target: build-final
      args:
        - PYTORCH_BASE_IMAGE=ghcr.io/futursolo/pai-apps/base:pytorch-v2.13.0-xpu-20260817
        - COMFYUI_VERSION=v0.36.0
    platform: linux/amd64
    image: ghcr.io/futursolo/pai-apps/comfyui:v0.36.0-pytorch-v2.13.0-xpu${PAI_BUILD_VERSION_SUFFIX}
  xpu-variant:
    extends: xpu
    image: ghcr.io/futursolo/pai-apps/comfyui:xpu${PAI_BUILD_VARIANT_SUFFIX}
