---
name: example-base-pytorch

services:
  base-pytorch:
    build:
      dockerfile: ./base/pytorch-ipex/Dockerfile
      context: ../..
    image: ghcr.io/futursolo/portable-ai/base:pytorch-ipex
    devices:
      - /dev/dri:/dev/dri
    environment:
      TZ: Etc/UTC
    group_add:
      - video
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
