ARG ROCM_IMAGE=rocm/dev-ubuntu-24.04:6.4.2

FROM ${ROCM_IMAGE} AS build-rocm

FROM ubuntu:24.04 AS build-final

ENV TZ=Etc/UTC

RUN  --mount=type=bind,source=./_base/_scripts/,target=/tmp/_build/ \
    /tmp/_build/create-pai-user.sh

RUN  --mount=type=bind,source=./_base/_scripts/,target=/tmp/_build/ \
    --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
    --mount=target=/var/cache/apt,type=cache,sharing=locked \
    /tmp/_build/apt-pre.sh

RUN  --mount=type=bind,source=./_base/_scripts/,target=/tmp/_build/ \
    --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
    --mount=target=/var/cache/apt,type=cache,sharing=locked \
    /tmp/_build/apt-install-python3.sh

RUN  --mount=type=bind,source=./_base/rocm/_scripts/,target=/tmp/_build/ \
    --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
    --mount=target=/var/cache/apt,type=cache,sharing=locked \
    /tmp/_build/apt-install-rocminfo-deps.sh

COPY --from=build-rocm /opt/amdgpu/ /opt/amdgpu/
COPY --from=build-rocm /opt/rocm/ /opt/rocm/
