---
name: build-base

services:
  pytorch-rocm:
    build:
      target: build-pytorch-rocm-final
      dockerfile: ./_base/rocm/Dockerfile
      context: ../
    platform: linux/amd64
    image: ghcr.io/futursolo/pai-apps/base:pytorch-v2.12.0-rocm-v7.14.0${PAI_BUILD_VERSION_SUFFIX}

  intel:
    build:
      target: build-intel-final
      dockerfile: ./_base/intel/Dockerfile
      context: ../
    platform: linux/amd64
    image: ghcr.io/futursolo/pai-apps/base:intel${PAI_BUILD_VERSION_SUFFIX}

  pytorch-xpu:
    build:
      target: build-pytorch-xpu-final
      dockerfile: ./_base/intel/Dockerfile
      context: ../
    platform: linux/amd64
    image: ghcr.io/futursolo/pai-apps/base:pytorch-v2.13.0-xpu${PAI_BUILD_VERSION_SUFFIX}

  vulkan:
    build:
      target: build-vulkan-final
      dockerfile: ./_base/vulkan/Dockerfile
      context: ../
    platform: linux/amd64
    image: ghcr.io/futursolo/pai-apps/base:vulkan${PAI_BUILD_VERSION_SUFFIX}
