---
name: build-base

services:
  rocm:
    build:
      target: build-rocm-final
      dockerfile: ./_base/rocm/Dockerfile
      context: ../
    platform: linux/amd64
    image: ghcr.io/futursolo/pai-apps/base:rocm-v7.1.1${PAI_BUILD_VERSION_SUFFIX}

  blas-rocm:
    build:
      target: build-blas-rocm-final
      dockerfile: ./_base/rocm/Dockerfile
      context: ../
    platform: linux/amd64
    image: ghcr.io/futursolo/pai-apps/base:blas-rocm-v7.1.1${PAI_BUILD_VERSION_SUFFIX}

  pytorch-rocm:
    build:
      target: build-pytorch-rocm-final
      dockerfile: ./_base/rocm/Dockerfile
      context: ../
    platform: linux/amd64
    image: ghcr.io/futursolo/pai-apps/base:pytorch-v2.9.1-rocm-v7.1.1${PAI_BUILD_VERSION_SUFFIX}

  intel:
    build:
      target: build-intel-final
      dockerfile: ./_base/intel/Dockerfile
      context: ../
    platform: linux/amd64
    image: ghcr.io/futursolo/pai-apps/base:intel${PAI_BUILD_VERSION_SUFFIX}

  pytorch-xpu:
    build:
      target: build-pytorch-xpu-final
      dockerfile: ./_base/intel/Dockerfile
      context: ../
    platform: linux/amd64
    image: ghcr.io/futursolo/pai-apps/base:pytorch-v2.9.1-xpu${PAI_BUILD_VERSION_SUFFIX}

  vulkan:
    build:
      target: build-vulkan-final
      dockerfile: ./_base/vulkan/Dockerfile
      context: ../
    platform: linux/amd64
    image: ghcr.io/futursolo/pai-apps/base:vulkan${PAI_BUILD_VERSION_SUFFIX}
