---
name: example-koboldcpp

services:
  koboldcpp:
    build:
      dockerfile: ./koboldcpp/rocm/Dockerfile
      context: ../..
    image: ghcr.io/futursolo/pai-apps/koboldcpp:rocm
    devices:
      - /dev/dri
      - /dev/kfd
    environment:
      HSA_OVERRIDE_GFX_VERSION: 11.0.0
    group_add:
      - video
      - $GROUP_ID_RENDER  # See README.md about how to obtain this ID.
    networks:
      # app_tier has no Internet access.
      # Ingress traffic is forwarded via the ingress container.
      - app_tier
    restart: unless-stopped
    command: >
      --contextsize 8192
      --model /mnt/models/Llama-3.3-70B-Instruct-Q4_K_M.gguf
      --usecublas --port 5001 --quiet
      --password mypassword
    security_opt:
      - seccomp:unconfined
    volumes:
      - read_only: true
        source: ../../../test-models
        target: /mnt/models
        type: bind

  # We accept traffic with the ingress container and forward it to the app.
  ingress:
    image: alpine/socat:latest
    depends_on:
      koboldcpp:
        condition: service_started
    ports:
      - 5001:5001
    networks:
      - app_tier
      - ingress_tier
    command: "TCP-LISTEN:5001,fork,reuseaddr TCP4:koboldcpp:5001"

networks:
  app_tier:
    internal: true
  ingress_tier:
