---
name: example-koboldcpp

services:
  koboldcpp:
    build:
      dockerfile: ./koboldcpp/rocm/Dockerfile
      context: ../..
    image: ghcr.io/futursolo/portable-ai/koboldcpp:v1.97.4.yr0-rocm-v6.4.3
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    environment:
      HSA_OVERRIDE_GFX_VERSION: 11.0.0
      PYTORCH_ROCM_ARCH: gfx1100
      TZ: Etc/UTC
    group_add:
      - video
      - render
    ports:
      - 5001:5001
    restart: unless-stopped
    command: >
      --contextsize 8192
      --model /home/docker-user/models/Llama-3.3-70B-Instruct-Q4_K_M.gguf
      --usecublas --port 5001 --quiet
      --password mypassword
    security_opt:
      - seccomp:unconfined
    volumes:
      - read_only: true
        source: ../../test-models
        target: /home/docker-user/models
        type: bind
