---
name: example-koboldcpp

services:
  koboldcpp:
    build:
      dockerfile: ./koboldcpp/vulkan/Dockerfile
      context: ../..
    image: ghcr.io/futursolo/pai-apps/koboldcpp:v1.97.4-vulkan
    devices:
      - /dev/dri
    group_add:
      - video
      - render
    ports:
      - 5001:5001
    restart: unless-stopped
    command: >
      --contextsize 8192
      --model /mnt/models/Llama-3.3-70B-Instruct-Q4_K_M.gguf
      --usevulkan --port 5001 --quiet
      --password mypassword
    security_opt:
      - seccomp:unconfined
    volumes:
      - read_only: true
        source: ../../../test-models
        target: /mnt/models
        type: bind
