---
name: example-koboldcpp

services:
  koboldcpp:
    build:
      dockerfile: ./koboldcpp/vulkan/Dockerfile
      context: ../..
    image: ghcr.io/futursolo/pai-apps/koboldcpp:v1.97.4-vulkan
    devices:
      - /dev/dri
    group_add:
      - video
      - render
    networks:
      # app_tier has no Internet access.
      # Ingress traffic is forwarded via the ingress container.
      - app_tier
    restart: unless-stopped
    command: >
      --contextsize 8192
      --model /mnt/models/Llama-3.3-70B-Instruct-Q4_K_M.gguf
      --usevulkan --port 5001 --quiet
      --password mypassword
    security_opt:
      - seccomp:unconfined
    volumes:
      - read_only: true
        source: ../../../test-models
        target: /mnt/models
        type: bind

  # We accept traffic with the ingress container and forward it to the app.
  ingress:
    image: alpine/socat:latest
    depends_on:
      koboldcpp:
        condition: service_started
    ports:
      - 5001:5001
    networks:
      - app_tier
      - ingress_tier
    command: "TCP-LISTEN:5001,fork,reuseaddr TCP4:koboldcpp:5001"

networks:
  app_tier:
    internal: true
  ingress_tier:
