---
on:
  workflow_dispatch:
    inputs:
      variant:
        description: "Image Variant"
        required: true
        type: choice
        options:
          - pytorch-rocm
          - pytorch-ipex
          - intel

name: Build Base Container

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build base:${{ github.event.inputs.variant }}
    permissions:
      contents: write
      packages: write

    steps:
      - name: Stop Docker Service
        run: |
          sudo systemctl stop docker.service
          sudo systemctl stop docker.socket

      - name: Remove Docker Data
        run: |
          sudo rm -rf /var/lib/docker
          sudo mkdir -p /var/lib/docker

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 1024
          swap-size-mb: 1024
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          build-mount-path: /var/lib/docker

      - name: Show Disk Space
        run: df -h

      - name: Start Docker Service
        run: |
          sudo systemctl start docker.service
          sudo systemctl start docker.socket

      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read Version
        run: echo "BASE_IMAGE_VERSION=$(cat .image-version)" >> $GITHUB_ENV
        working-directory: "base/${{ github.event.inputs.variant }}"

      - name: Define Versions (Release)
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          _DATE_VER=$(date +'%Y%m%d')
          IMAGE_VERSION=${BASE_IMAGE_VERSION}-${_DATE_VER}

          echo "IMAGE_VERSION=${IMAGE_VERSION}" >> $GITHUB_ENV

      - name: Define Versions (Preview)
        if: ${{ github.ref != 'refs/heads/master' }}
        run: |
          _DATE_VER=$(date +'%Y%m%d')
          IMAGE_VERSION=${BASE_IMAGE_VERSION}-preview

          echo "IMAGE_VERSION=${IMAGE_VERSION}" >> $GITHUB_ENV

      - name: Build and Push base:${{ env.IMAGE_VERSION }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: base/${{ github.event.inputs.variant }}/Dockerfile
          push: true
          tags: |
            ghcr.io/futursolo/portable-ai/base:${{ env.IMAGE_VERSION }}
